import React,{useState} from 'react';

function Help() {

  // Set the state if help displays or not
  const[helpState,setHelpState] = useState(false);

// The instructions (and close) button if the user gets stuck.
  const displayHelpToUser = ( 
    <div>
      <p><u> How to play: </u></p>
      <ul>
        <li>A word will be autogenerated.</li>
        <li>There is a dash for every letter of the word.</li>
        <li>You choose a letter from the buttons displayed.</li>
        <li>If you select a letter that is in the word, the computer will fill in the blanks wherever the letter occurs in the word. </li>
        <li>If you get too many incorrect letters, you will lose the game.</li>
      </ul>
      <p><u> Objective: </u></p>
      <ul>
        <li>Guess the correct word(s) before HANGMAN! </li>
      </ul><br/>
      <button onClick={()=>{setHelpState(false)}}>Close</button>
    </div>
  )

  // Button to click on if user needs help
  const doNotDisplayHelp = (
    <div>
      <button onClick={()=>{setHelpState(true)}}>How to play</button>
    </div>
  )

  // Return true/false based on state 
  return (<div>
    {helpState? displayHelpToUser : doNotDisplayHelp}
    </div>)
}

export default Help